name: Deploy React to GitHub Pages

on:
  # Körs när du pushar till main-grenen
  push:
    branches: ["main"]

  # Gör att du kan köra den manuellt från Actions-fliken
  workflow_dispatch:

# Ger GITHUB_TOKEN rättigheter att deploya
permissions:
  contents: read
  pages: write
  id-token: write

# Tillåter bara en deploy åt gången
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env: # Här kopplar vi GitHubs secret till Vites bygg-process
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}

      - name: Create 404.html
        # Detta kopierar index.html till 404.html i dist-mappen
        run: cp ./dist/index.html ./dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # VIKTIGT: Ändra till './dist' om du använder Vite!
          # Använd './build' om du använder Create React App (CRA).
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4